In [ ]:
#1. Problem: Find Longest Substring Without Repeating Characters

In [ ]:
def longest_substring(s):
    front = 0
    max_length = 0
    char_index = {} #store last index of character

    for back in range(len(s)):
      if s[back] in char_index and char_index[s[back]] >= front:
        front = char_index[s[back]]+1 # moving front past previous occurrence
      char_index[s[back]]=back #updating last seen
      max_length= max(max_length, len(s[front:back+1])) #length of substring using slicing

    return max_length

s = input("Enter a string: ")
print(f"The length of the longest substring without repeating characters is {longest_substring(s)}")

Enter a string: abcabcbb
The length of the longest substring without repeating characters is 3


In [ ]:
#3. Problem: Write a Python program to solve the quadratic equation of the form ax^2 + bx + c = 0 for given a, b, and c. The program should return the two roots (if they exist) or a message if the equation has no real roots.

In [ ]:
from math import sqrt

#check if b^2-4ac > 0 (2 real roots) or = 0 (one real root) or < 0 (no real roots)

def solve_quadratic(a, b, c):
    discriminant = b**2 - 4 * a * c
    if discriminant > 0:
       root1 = (-b+sqrt(b**2-4*a*c))/2*a
       root2 = (-b-sqrt(b**2-4*a*c))/2*a
       return root1, root2
    elif discriminant == 0:
        root = -b/2*a
        return root
    else:
        return "No real roots"

a, b, c = 1, -3, 2
result = solve_quadratic(a, b, c)
print(f"The roots are: {result}")

The roots are: (2.0, 1.0)


In [ ]:
#5. Problem: Write a Python program to find all Armstrong numbers between two numbers n1 and n2.

In [ ]:
def is_armstrong(n):
    num_digits = 0
    temp = n
    while temp > 0:
      num_digits += 1
      temp //= 10

    sum_of_powers = 0
    temp = n
    while temp > 0:
      digit = temp % 10
      sum_of_powers += digit ** num_digits
      temp //= 10
    return sum_of_powers == n

def armstrong_numbers_in_range(n1, n2):
  armstrong_numbers = []
  for n in range(n1, n2+1):
      if is_armstrong(n):
          armstrong_numbers.append(n)
  return armstrong_numbers

n1, n2 = 100, 999
print(f"Armstrong numbers between {n1} and {n2}: {armstrong_numbers_in_range(n1, n2)}")

Armstrong numbers between 100 and 999: [153, 370, 371, 407]


In [ ]:
# 6. Problem: Create a program that simulates a simple bank account system. The program should allow a user to perform the following operations:
# a. Check balance
# b. Deposit money
# c. Withdraw money
# d. Exit the program
# Implement this system using loops to keep the program running until the user decides to exit.

In [ ]:
def bank_account_system():
    balance = 1000  # initial balance
    while True:
        print("\n--- Bank Account System ---")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")
        choice = int(input("Enter your choice: "))

        if choice == 1:
            print(f"Your balance is Rs.{balance}")
        elif choice == 2:
            amt = float(input("Enter the amt to deposit: Rs."))
            balance += amt
            print(f"Rs.{amt} deposited")
        elif choice == 3:
            amt = float(input("Enter the amt to withdraw: Rs."))
            if amt <= balance:
                balance -= amt
                print(f"Rs.{amt} withdrawn")
            else:
                print("not enough money")
        elif choice == 4:
            print("Exiting the system. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")

bank_account_system()



--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Rs.500.0 deposited

--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Your balance is Rs.1500.0

--- Bank Account System ---
1. Check Balance
2. Deposit Money
3. Withdraw Money
4. Exit
Exiting the system. Goodbye!


In [ ]:
#Calculate the mean, median, mode, standard deviation, and variance for the dataset:

In [ ]:
import statistics as sts

data = [5.0,10.0,15.0,20.0,25.0,30.0,35.0]

mean_data = sts.mean(data)
median_data = sts.median(data)
mode_data = sts.mode(data)
var_data = sts.variance(data)
stddev_data = var_data ** 0.5

print(f"mean is {mean_data}")
print(f"median is {median_data}")
print(f"mode is {mode_data}")
print(f"variance is {var_data}")
print(f"standard deviation is {stddev_data}")

mean is 20.0
median is 20.0
mode is 5.0
variance is 116.66666666666667
standard deviation is 10.801234497346433


In [ ]:
#Generate a random data set of size 100 with values between 1 and 50. Calculate all the statistical measures discussed above.

In [ ]:
import random
import numpy as np

data = [random.randint(1,50) for _ in range(100)]

mean_data = np.mean(data)
median_data = np.median(data)
mode_data = sts.mode(data)
var_data = sts.variance(data)
stddev_data = var_data ** 0.5

print(f"mean is {mean_data}")
print(f"median is {median_data}")
print(f"mode is {mode_data}")
print(f"variance is {var_data}")
print(f"standard deviation is {stddev_data}")

mean is 25.54
median is 25.5
mode is 29
variance is 153.32161616161616
standard deviation is 12.382310614809183


In [ ]:
#Create a 5x5 array filled with random integers from 0 to 10.

In [ ]:
data = np.random.randint(0,10,size=(5,5))
row_vec = np.array([1,1,2,3,5])
new = data + row_vec
multi_array = new*row_vec.reshape(5,1)
print(multi_array)

[[ 6  4  3  9  6]
 [ 9 10  3  7  8]
 [18 14 14  6 28]
 [24 27 27 21 30]
 [40 50 30 25 55]]


In [ ]:
# Array Manipulation

In [ ]:
data = np.random.randint(1,20,size=(1,20))
new = data.reshape(4,5)
newnew = new.flatten()

mean_data = np.mean(newnew)
var_data = sts.variance(newnew.tolist())
stddev_data = var_data ** 0.5
sum_data = np.sum(newnew)

print(f"mean is {mean_data}")
print(f"standard deviation is {stddev_data}")
print(f"sum is {sum_data}")

mean is 10.75
standard deviation is 5.369259480451755
sum is 215
